//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Fotografix.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_COLOR                       128
#define IDR_DOCTYPE                     129
#define IDD_NEWIMAGE                    130
#define ID_INDICATOR_ZOOM               130
#define ID_INDICATOR_SIZE               131
#define ID_INDICATOR_LAYER              132
#define IDB_COLOR2                      132
#define ID_INDICATOR_CHANNEL            133
#define IDB_COLOR1                      133
#define IDD_CANVASSIZE                  134
#define IDR_SELECT                      135
#define IDR_TOOLS                       136
#define IDR_WAND                        136
#define IDC_HAND2                       138
#define IDC_CROSS2                      139
#define IDC_DROPPER                     140
#define IDC_MOVE                        141
#define IDD_ADJUST                      142
#define IDR_LAYERS                      143
#define IDR_POPUP                       143
#define IDR_BRUSH                       144
#define IDR_DUMMY                       145
#define IDD_INPUT                       146
#define IDD_FILL                        147
#define IDD_IMAGESIZE                   148
#define IDD_LAYER                       149
#define IDR_GRADIENT                    150
#define IDD_TEXT                        151
#define IDI_ADJUST                      155
#define IDI_LAYER                       156
#define IDI_TEXT                        157
#define IDD_RAWIMPORT                   160
#define IDR_SCRIPTS                     161
#define IDI_FILE                        164
#define IDI_FOLDER                      165
#define IDC_HAND3                       166
#define IDC_ZOOM                        169
#define IDI_ZOOM                        176
#define IDI_SIZE                        177
#define IDD_JPEG_OPTIONS                178
#define IDD_RULER                       179
#define IDC_W1                          1000
#define IDC_H1                          1001
#define IDC_W2                          1002
#define IDC_HEADER                      1002
#define IDC_H2                          1003
#define IDC_FILL                        1004
#define IDC_RES                         1005
#define IDC_FGCOLOR                     1005
#define IDC_BGCOLOR                     1006
#define IDC_DEFAULT                     1007
#define IDC_SWAP                        1008
#define IDC_UNIT                        1009
#define IDC_ANCHOR                      1010
#define IDC_RELATIVE                    1011
#define IDC_SELSTYLE                    1012
#define IDC_SELW                        1013
#define IDC_SELH                        1014
#define IDC_TOLERANCE                   1015
#define IDC_WAND                        1016
#define IDC_PREVIEW                     1016
#define IDC_RESAMPLE                    1016
#define IDC_AA                          1016
#define IDC_LABEL1                      1017
#define IDC_CONSTRAIN                   1017
#define IDC_LABEL2                      1018
#define IDC_LABEL3                      1019
#define IDC_EDIT1                       1020
#define IDC_LAYERS                      1020
#define IDC_EDIT2                       1021
#define IDC_EDIT3                       1022
#define IDC_SLIDER1                     1023
#define IDC_SLIDER2                     1024
#define IDC_SLIDER3                     1025
#define IDC_RESET1                      1026
#define IDC_RESET2                      1027
#define IDC_BRUSH                       1027
#define IDC_RESET3                      1028
#define IDC_CHANNEL                     1028
#define IDC_PROMPT                      1029
#define IDC_VALUE                       1030
#define IDC_COLOUR                      1031
#define IDC_OPACITY                     1032
#define IDC_GRADCOLOR                   1033
#define IDC_GRADTYPE                    1034
#define IDC_CHOOSE                      1034
#define IDC_TEXT                        1035
#define IDC_COLOR                       1036
#define IDC_SIZE                        1038
#define IDC_W                           1039
#define IDC_H                           1040
#define IDC_MODE                        1041
#define IDC_SCRIPTS                     1042
#define IDC_FEEDBACK                    1044
#define IDC_PRESET                      1045
#define IDC_HEADER1                     1046
#define IDC_HEADER2                     1047
#define IDC_RESUNIT                     1047
#define IDC_RESLABEL                    1049
#define IDC_NAME                        1050
#define IDC_PT1                         1051
#define IDC_PT2                         1052
#define IDC_DISTANCE                    1053
#define IDL_OPACITY                     1053
#define IDC_DISTANCE2                   1054
#define IDC_ANGLE                       1054
#define IDC_EXTRA                       1054
#define ID_TOOL_RSELECT                 10000
#define ID_TOOL_ESELECT                 10001
#define ID_TOOL_WAND                    10002
#define ID_TOOL_MOVE                    10003
#define ID_TOOL_TRANSFORM               10004
#define ID_TOOL_RULER                   10005
#define ID_TOOL_BRUSH                   10006
#define ID_TOOL_ERASER                  10007
#define ID_TOOL_CLONE                   10008
#define ID_TOOL_FILL                    10009
#define ID_TOOL_GRADIENT                10010
#define ID_TOOL_TEXT                    10011
#define ID_TOOL_DROPPER                 10012
#define ID_TOOL_HAND                    10013
#define ID_TOOL_ZOOM                    10014
#define ID_ADJUSTMENTS_BRIGHTNESS       20000
#define ID_ADJUSTMENTS_COLOURBALANCE    20001
#define ID_ADJUSTMENTS_DESATURATE       20002
#define ID_ADJUSTMENTS_BLACKWHITE       20003
#define ID_ADJUSTMENTS_GRADIENTMAP      20004
#define ID_ADJUSTMENTS_INVERT           20005
#define ID_ADJUSTMENTS_THRESHOLD        20006
#define ID_ADJUSTMENTS_POSTERIZE        20007
#define ID_ADJUSTMENTS_LEVELS           20008
#define ID_FILTER_BLUR                  20020
#define ID_FILTER_MOTIONBLUR            20021
#define ID_FILTER_GAUSSIANBLUR          20022
#define ID_FILTER_ADDNOISE              20023
#define ID_FILTER_EMBOSS                20024
#define ID_FILTER_SHEAR                 20025
#define ID_FILTER_SOLARIZE              20026
#define ID_FILTER_OFFSET                20027
#define ID_FILTER_PIXELATE              20028
#define ID_FILTER_NIGHTVISION           20029
#define ID_FILTER_HALFTONE              20030
#define ID_FILTER_SHARPEN               20031
#define ID_FILTER_UNSHARPMASK           20032
#define ID_FILTER_EDGES_ALL             20033
#define ID_FILTER_EDGES_HORIZONTAL      20034
#define ID_FILTER_EDGES_VERTICAL        20035
#define ID_FILTER_EDGES_DIAGONAL        20036
#define ID_LAYER_BRIGHTNESS             30000
#define ID_LAYER_COLOURBALANCE          30001
#define ID_LAYER_DESATURATE             30002
#define ID_LAYER_BLACKWHITE             30003
#define ID_LAYER_GRADIENTMAP            30004
#define ID_LAYER_INVERT                 30005
#define ID_LAYER_THRESHOLD              30006
#define ID_LAYER_POSTERIZE              30007
#define ID_LAYER_LEVELS                 30008
#define ID_EDIT_PURGEUNDO               32773
#define ID_SELECT_ALL                   32774
#define ID_SELECT_DESELECT              32775
#define ID_SELECT_INVERSE               32776
#define ID_EDIT_SELECTALL               32777
#define ID_IMAGE_CROP                   32784
#define ID_IMAGE_REVEALALL              32785
#define ID_VIEW_ZOOMIN                  32786
#define ID_VIEW_ZOOMOUT                 32787
#define ID_VIEW_SCALETOFIT              32788
#define ID_VIEW_ACTUALSIZE              32789
#define ID_VIEW_FULLSCREEN              32790
#define ID_IMAGE_CANVASSIZE             32791
#define ID_WINDOW_COLOUR                32813
#define ID_WINDOW_LAYERS                32814
#define ID_WINDOW_TOOLS                 32815
#define ID_LAYER_NEW                    32821
#define ID_NEW_LAYERVIACOPY             32823
#define ID_NEW_LAYERVIACUT              32824
#define ID_LAYER_DUPLICATELAYER         32825
#define ID_LAYER_PROPERTIES             32834
#define ID_LAYER_DELETELAYER            32835
#define ID_LAYER_DELETE                 32836
#define ID_LAYER_RENAMELAYER            32838
#define ID_LAYER_RENAME                 32839
#define ID_EDIT_PURGECLIPBOARD          32843
#define ID_EDIT_PURGEALL                32845
#define ID_LAYER_ADDLAYERMASK           32849
#define ID_LAYER_REMOVELAYERMASK        32850
#define ID_LAYER_ENABLELAYERMASK        32851
#define ID_EDIT_FILL                    32854
#define ID_IMAGE_IMAGESIZE              32857
#define ID_IMAGE_FLIP                   32860
#define ID_FLIP_HORIZONTAL              32861
#define ID_FLIP_VERTICAL                32862
#define ID_LAYER_MOVEUP                 32863
#define ID_LAYER_MOVEDOWN               32864
#define ID_FILE_EXTRACT                 32873
#define ID_SELECT_LAYERTRANSPARENCY     32874
#define ID_LAYER_RASTERIZE              32879
#define ID_MODIFY_EXPAND                32885
#define ID_MODIFY_CONTRACT              32886
#define ID_MODIFY_FEATHER               32887
#define ID_EDIT_FILL_FG                 32906
#define ID_EDIT_FILL_BG                 32907
#define ID_WINDOW_SCRIPTS               32908
#define ID_IMAGE_ROTATE                 32912
#define ID_ROTATE_90                    32913
#define ID_ROTATE_180                   32914
#define ID_ROTATE_270                   32915
#define ID_ROTATE_OTHER                 32916
#define ID_TRANSFORM_FLIPHORIZONTAL     32920
#define ID_TRANSFORM_FLIPVERTICAL       32921
#define ID_TRANSFORM_ROTATE90           32922
#define ID_TRANSFORM_ROTATE180          32923
#define ID_TRANSFORM_ROTATE270          32924
#define ID_TRANSFORM_ROTATEBYANGLE      32925
#define ID_LAYER_MERGEDOWN              32928
#define ID_LAYER_FLATTENIMAGE           32929
#define IDC_PREVBRUSH                   32932
#define IDC_NEXTBRUSH                   32933
#define ID_EDIT_PASTEEXTERNAL           32934
#define ID_PRESET                       32936
#define ID_PRESET_A4                    32937
#define ID_PRESET_A3                    32938
#define ID_PRESET_A2                    32939
#define ID_PRESET_LETTER                32940
#define ID_PRESET_CLIPBOARD             32941
#define ID_PRESET_WINDOWSCLIPBOARD      32942
#define ID_PRESET_WINDOWS               32943
#define ID_APP_LANGUAGE                 32983

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32987
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
